version: "3.9"

services:  
  backend:
    image: edroplets_backend
    container_name: edroplets_backend
    ports:
      - 3000:3000
    restart: on-failure
    environment:
      # to reset database, pass in as `RESET_DATABASE=Yes; docker-compose up`
      - RESET_DATABASE=$RESET_DATABASE
      # to migrate database, pass in as `MIGRATE_DATABASE=Yes; docker-compose up`
      - MIGRATE_DATABASE=$MIGRATE_DATABASE
      - FORCE_COLOR=1
