version: "3.7"

# https://start.jcolemorrison.com/authorized-resources-and-database-migrations-with-strongloops-loopback/

services:  
  edrop_mysqldb:
    image: mysql:8.0 # max version supported by AWS RDS
    container_name: edrop_mysqldb
    env_file:
      - ./deploy/dev/mysql.env
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - dockerdbdev:/var/lib/mysql # persistent storage for DB

  edrop_backend:
    volumes:
      - ./server/:/usr/src/app
    env_file:
      - ./deploy/dev/backend.env
    depends_on:
      - edrop_mysqldb # start database before backend
  
  edrop_ngrok:
    # for local dev development, to receive Shopify webhooks
    image: wernight/ngrok:latest
    container_name: edrop_ngrok
    env_file:
      - ./deploy/dev/ngrok.env
    ports:
      - 4040:4040 # ngrok web interface

volumes:
  dockerdbdev: 
