version: "3.9"

# https://start.jcolemorrison.com/authorized-resources-and-database-migrations-with-strongloops-loopback/

services:
  edrop_backend:
    env_file:
      - ./deploy/prod/backend.env
    depends_on:
      - edrop_caddy
  
  edrop_caddy:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./deploy/prod/caddy.env
    container_name: edrop_caddy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/client/dist:/usr/share/caddy/www
      - $PWD/community/dist:/usr/share/caddy/community
      - /home/ubuntu/caddy/data:/data
      - /home/ubuntu/caddy/config:/config

volumes:
  caddy_data:
    external: true
  caddy_config:
