version: "3.7"

# https://start.jcolemorrison.com/authorized-resources-and-database-migrations-with-strongloops-loopback/

services:  
  edrop_backend:
    image: edrop_backend
    container_name: edrop_backend
    ports:
      - 3000:3000
    restart: on-failure
    environment:
      # to reset database, pass in as `RESET_DATABASE=Yes; docker-compose up`
      - RESET_DATABASE=$RESET_DATABASE
      # to migrate database, pass in as `MIGRATE_DATABASE=Yes; docker-compose up`
      - MIGRATE_DATABASE=$MIGRATE_DATABASE
