version: "3.9"

services:
  backend:
    env_file:
      - ./deploy/prod/backend.env
    environment:
      - PROD_RESET_DATABASE=$PROD_RESET_DATABASE
    depends_on:
      - caddy
  
  caddy:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./deploy/prod/caddy.env
    container_name: edroplets_caddy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/client/dist:/usr/share/caddy/www
      - $PWD/community/dist:/usr/share/caddy/community
      - /home/ubuntu/caddy/data:/data
      - /home/ubuntu/caddy/config:/config

volumes:
  caddy_data:
    external: true
  caddy_config:
