version: "3.9"

services:  
  edrop_backend:
    env_file:
      - ./deploy/prod/aws.env
  
  edrop_ngrok:
    # for local dev development, to receive Shopify webhooks
    image: wernight/ngrok:latest
    container_name: edrop_ngrok
    env_file:
      - ./deploy/dev/ngrok.env
    ports:
      - 4040:4040 # ngrok web interface

volumes:
  dockerdbdev:
