import {Entity, model, property} from '@loopback/repository';

@model({settings: {description: 'Order item base information'}})
export class OrderItem extends Entity {
  @property({
    type: 'number',
    id: 1,
    generated: true,
    updateOnly: true,
  })
  id?: number;

  @property({
    type: 'string',
    required: true,
    description: 'Product ID generated by Shopify',
  })
  productIdShopify: string;

  @property({
    type: 'string',
    required: true,
    description: 'Variant ID generated by Shopify',
  })
  variantIdShopify: string;

  @property({
    type: 'string',
    required: true,
    description: 'Line item ID in checkout generated by Shopify',
  })
  lineItemIdShopify: string;

  @property({
    type: 'string',
    required: true,
    description: 'Name of product',
  })
  name: string;

  @property({
    type: 'string',
    required: true,
    description: 'Product description generated by Shopify',
  })
  description: string;

  @property({
    type: 'number',
    required: true,
  })
  quantity: number;

  @property({
    type: 'number',
    required: true,
    description: 'Cost per item for this variant',
  })
  price: number;

  @property({
    type: 'string',
  })
  otherDetails?: string;

  @property({
    type: 'number',
  })
  orderInfoId?: number;

  constructor(data?: Partial<OrderItem>) {
    super(data);
  }
}

export interface OrderItemRelations {
  // describe navigational properties here
}

export type OrderItemWithRelations = OrderItem & OrderItemRelations;
