export * from './before-checkout';
export * from './check-email';
export * from './chip-fab';
export * from './coming-soon';
export * from './email-unverified';
export * from './email-verified';
export * from './forgot-password';
export * from './home';
export * from './login';
export * from './manage/address';
export * from './manage/address/new';
export * from './manage/address/update';
export * from './manage/admins';
// export * from './manage/admins/add';
// export * from './manage/admins/update';
export * from './manage/cart';
export * from './manage/change-password';
export * from './manage/chip-orders';
export * from './manage/files';
export * from './manage/chip-orders';
export * from './manage/orders';
export * from './manage/profile';
export * from './manage/customers';
export * from './manage/workers';
export * from './not-found';
export * from './product';
export * from './products';
export * from './project';
export * from './signup';
export * from './reset-password';
// export * from './shop';
export * from './upload';
export * from './subpage/order-chat';
export * from './subpage/order-detail';