export default {
  ADMIN_ROLE_ID: 1,
  ADMIN_ROLE_NAME: 'admin',
  ADMIN: 'ADMIN',

  CUSTOMER_ROLE_ID: 2,
  CUSTOMER_ROLE_NAME: 'customer',
  CUSTOMER: 'CUSTOMER',

  WORKER_ROLE_ID: 3,
  WORKER_ROLE_NAME: 'worker',
  WORKER: 'WORKER',
};
