name: End-to-end tests
on:
    push:
        # Triggers on push to stage or master
        branches: [stage, master]
    workflow_dispatch:
jobs:
    cypress-run:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18]

        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Write env variables
              run: |
                  echo "APP_PUSHER_API_KEY=${{ secrets.APP_PUSHER_API_KEY }}" >> ./deploy/test/backend.env
                  echo "APP_PUSHER_API_SECRET=${{ secrets.APP_PUSHER_API_SECRET }}" >> ./deploy/test/backend.env
            # Install NPM dependencies, cache them correctly
            # and run all Cypress tests
            - name: Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install rimraf
              run: npm install -g rimraf
            - name: Build middleware packages
              run: |
                  cd api
                  npm run build
                  cd ../schemas
                  npm run build
              working-directory: ./packages
            - name: Install client dependencies
              run: npm install
              working-directory: ./client
            - name: Install community dependencies
              run: npm install
              working-directory: ./community
              
